spring.application.name=student-portal
server.port=8080

spring.datasource.url=jdbc:h2:mem:student_portal
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.cors.allowed-origins=http://localhost:8080,http://127.0.0.1:8080,null